---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

    - name: Installing initial applications
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - htop
          - curl
          - wget
          - ncdu
          - tree
          - apt-transport-https
          - ca-certificates
          - gnupg
          - python3-pip
          - make
          - git
          - gnupg-agent
          - virtualbox
          - snapd
          - flatpak

    - block:
      - name: Installing NodeJS
        shell: 
          cmd: 'curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -'
          warn: false
      - name: Installing npm
        become: true
        apt:
          name: nodejs

    - name: Updating repositories
      become: true
      apt:
        update_cache: yes

    - name: Installing Dependencies to Ruby-2.7.6
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - autoconf 
          - bison 
          - build-essential 
          - libssl-dev 
          - libyaml-dev 
          - libreadline6-dev 
          - zlib1g-dev 
          - libncurses5-dev 
          - libffi-dev 
          - libgdbm6 
          - libgdbm-dev 
          - libdb-dev
          - g++
          - gcc 
          - autoconf 
          - automake 
          - bison 
          - libc6-dev 
          - libffi-dev 
          - libgdbm-dev 
          - libncurses5-dev 
          - libsqlite3-dev 
          - libtool 
          - libyaml-dev 
          - pkg-config 
          - sqlite3 
          - zlib1g-dev 
          - libgmp-dev 
          - libreadline-dev 
          - libssl-dev

    - block:
      - name: Installing Homebrew
        shell: 
          cmd: 'curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh'
          warn: false       

      - name: Installing Rbenv
        shell: 
          cmd: 'curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash'
          warn: false         
 
      - name: Export Rbenv
        shell: |
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc 

      - name: Export Rbenv init
        shell: |
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc

      - name: Source Bashrc
        become: false   
        shell: source /home/{{ ansible_user_id }}/.bashrc
        args:
          executable: /bin/bash

      - name: Installing Ruby-2.7.6
        shell: 
          cmd: 'rbenv install 2.7.6'
          warn: false       

      - name: Installing Ruby-2.7.6 as the Global Version 
        shell: 
          cmd: 'rbenv global 2.7.6'
          warn: false       

    - block:
      - name: Flathub flatpak repo
        become: true
        flatpak_remote:
          name: flathub
          state: present
          flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
          method: system

      - name: Flatpak install package Figma
        flatpak:
          name: io.github.Figma_Linux.figma_linux
          state: present
           
      - name: Flatpak install package Teams
        flatpak:
          name: com.microsoft.Teams
          state: present

      - name: Flatpak install package Slack
        flatpak:
          name: com.slack.Slack
          state: present             
    
    - block:
      - name: Snap install package with tag
        become: true
        snap: 
            name: '{{ item }}'
        loop:
            - postman

      - name: Snap install packages with tag classic
        become: true
        snap: 
            name: '{{ item }}'
            classic: yes
        loop:
            - code
            - flutter
            - intellij-idea-ultimate
            - datagrip
            - android-studio

    - block:
      - name: Install Google Key
        become: true
        apt_key: 
          url: 'https://dl.google.com/linux/linux_signing_key.pub'
          state: present
      - name: Install Google Repository
        become: true
        shell: 
          cmd: 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          warn: false      
      - name: Updating repositories
        become: true
        apt:
         update_cache: yes          
      - name: Installing Google Chrome
        become: true
        apt:
          name: google-chrome-stable

    - block: 
      - name: Install Docker Key
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/ubuntu/gpg'
          state: present
      - name: Install Docker Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
          state: present
          filename: docker-ce
      - name: Install Docker
        become: true
        apt:
          name: docker-ce
      - name: Adding existing user to group Docker
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          groups: docker 
          append: yes
      - name: Installing Docker-Compose
        become: true
        get_url:
          url: 'https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64'
          dest: '/usr/local/bin/docker-compose'
          mode: 755
      - name: Install Docker Machine Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash'
          dest: '/etc/bash_completion.d/docker-machine'
      - name: Install Docker-Compose Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/compose/1.26.2/contrib/completion/bash/docker-compose'
          dest: '/etc/bash_completion.d/docker-compose'
      - name: Install Docker-Compose and Docker Machine Zsh Completion
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          regexp: '^plugins='
          line: 'plugins=(git docker docker-compose)'
        
    - block:
      - name: Adding Oracle Java 17 Repository
        become: true
        apt_repository:
          repo: 'ppa:linuxuprising/java'

      - name: Installing Repository Java 17 
        become: true
        shell: 
          cmd: 'echo "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu focal main" | tee /etc/apt/sources.list.d/linuxuprising-java.list'
          warn: false      

      - name: Importing Oracle Java 17 repository key
        become: true
        apt_key:
          keyserver: hkp://keyserver.ubuntu.com:80
          id: 73C3DB2A
          state: present

      - name: Updating repositories
        become: true
        apt:
         update_cache: yes

      - name: Installing Oracle Java 17 
        become: true
        apt:
          name: oracle-java17-installer 
          state: latest
          install_recommends: yes

      - name: Accepting Licenses
        shell: 
          cmd: 'echo oracle-java17-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections'
          warn: false  

    - block:
      - name: Installing a .deb package Insomnia
        become: true
        apt:
          deb: https://updates.insomnia.rest/downloads/ubuntu/latest?&app=com.insomnia.app&source=website
    
    - block:
      - name: Upgrade all packages to the latest version
        become: true
        apt:
          name: "*"
          state: latest

      - name: Removing dependencies that are no longer required
        become: true
        apt:
          autoremove: yes     

      - name: Removing useless packages from the cache
        become: true
        apt:
          autoclean: yes